### ISSUE TITLE
SettingSync should be able to read mod settings

### ISSUE THREAD

**Issue by Psychpsyo** [neos-modding-group/NeosModLoader#42]
It'd very nice if the SettingSync component could read mod settings by accessing a path like ModLoader.modname.setting
This would make editing mod settings more straightforward and consistent with base game settings.

**Comment by EIA485** [comment]
Seems like the sort of thing a mod can implement, I don't see a reason for this to be added to the loader. Could also cause some issues depending on what mod configs exist.
