### ISSUE TITLE
NML "tell" via loaded types

### ISSUE THREAD

**Issue by zkxs** [neos-modding-group/NeosModLoader#64]
LogiX can be used to make a user write a type such as `NeosModLoader.NeosMod`, `NeosModSettings.NeosModSettings`, etc into a TypeField and checking if it succeeded. This can be used to detect if users are running NML.

**Comment by zkxs** [comment]
from @XDelta in #61:
> I'd say our fix should be part of NML. Would be a better default than needing a mod

I agree. My intent was for a base NML install to be undetectable.

**Comment by EIA485** [comment]
just to cross pollinate my thoughts from #61
we should probably add the fix to the loader its self but have a config option to disable it.

**Comment by EIA485** [comment]
think il make a separate pr that implements the args pacing solution
