### ISSUE TITLE
ModConfigurationKey<Nullable<T>>.Validate does not pass when given a null

### ISSUE THREAD

**Issue by badhaloninja** [neos-modding-group/NeosModLoader#78]
ModConfigurationKey.Validate fails when giving null on a Nullable\<T> key

**Comment by zkxs** [comment]
This *should* be fixed in [1.12.4](https://github.com/neos-modding-group/NeosModLoader/releases/tag/1.12.4), but I haven't actually tested it myself.

**Comment by EIA485** [comment]
ive confirmed that #79 fixed the issue by testing against [Toxic-Cookie/GenericSettings](https://github.com/Toxic-Cookie/GenericSettings) with [badhaloninja/neosModSettings/](http://github.com/badhaloninja/neosModSettings/)
